{% set name = "celery" %}
{% set version = "3.1.25" %}
{% set sha256 = "6ced63033bc663e60c992564954dbb5c84c43899f7f1a04b739957350f6b55f3" %}
{% set build = 0 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - celery = celery.__main__:main
        - celeryd = celery.__main__:_compat_worker
        - celerybeat = celery.__main__:_compat_beat
        - celeryd-multi = celery.__main__:_compat_multi

requirements:
    build:
        - python
        - setuptools
        - pytz
        - billiard >=3.3.0.23,<3.4
        - kombu >=3.0.34,<4.0
    run:
        - python
        - pytz
        - billiard >=3.3.0.23,<3.4
        - kombu >=3.0.34,<4.0
        - sqlalchemy

test:
    imports:
        - celery
        - celery.app
        - celery.apps
        - celery.backends
        - celery.backends.database
        - celery.bin
        - celery.concurrency
        - celery.contrib
        - celery.events
        - celery.fixups
        - celery.loaders
        - celery.security
        - celery.task
        - celery.utils
        - celery.utils.dispatch
        - celery.worker
        
    commands:
        - celery --version
        - celery worker --help
        - celery beat --help
        - celery multi help
        - celery shell --help

about:
    home: http://celeryproject.org
    license_file: LICENSE
    license: BSD 3-Clause
    summary: Distributed Task Queue
    dev_url: https://github.com/celery/celery
    doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
    recipe-maintainers:
        - kwilcox
        - pmlandwehr
