{% set name = "celery" %}
{% set version = "4.3.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 4c4532aa683f170f40bd76f928b70bc06ff171a959e06e71bf35f2f9d6031ef9

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
        - celery = celery.__main__:main

requirements:
    build:
        - python
        - pip
    run:
        - python
        - pytz
        - billiard >=3.5.0.2,<3.6
        - kombu >=4.2.0,<5.0
        - sqlalchemy
        - cryptography

test:
    requires:
        - case >=1.3.1
        - pytest >=3.0
    source_files:
        - t
    imports:
        - celery
        - celery.app
        - celery.apps
        - celery.backends
        - celery.backends.database
        - celery.bin
        - celery.concurrency
        - celery.contrib
        - celery.events
        - celery.fixups
        - celery.loaders
        - celery.security
        - celery.task
        - celery.utils
        - celery.utils.dispatch
        - celery.worker

    commands:
        - celery --version
        - celery worker --help
        - celery beat --help
        - celery multi help
        - celery shell --help
        - pytest t/unit  # [py3k]

about:
    home: http://celeryproject.org
    license_file: LICENSE
    license: BSD 3-Clause
    summary: Distributed Task Queue
    dev_url: https://github.com/celery/celery
    doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
    recipe-maintainers:
        - kwilcox
        - pmlandwehr
        - sodre
