{% set name = "celery" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 313930fddde703d8e37029a304bf91429cd11aeef63c57de6daca9d958e1f255

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - celery = celery.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytz
    - billiard >=3.6.3,<4.0
    - kombu >=5.0.0,<6.0
    - vine >=5.0.0,<6.0
    - sqlalchemy
    - cryptography
  run_constrained:
    - sphinx >=2.0

test:
  requires:
    - boto3 >=1.9.178
    - case >=1.3.1
    - moto 1.3.7.*
    - pytest >=6.0.0
  source_files:
    - t
  imports:
    - celery
    - celery.app
    - celery.app.task
    - celery.apps
    - celery.backends
    - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.utils
    - celery.utils.dispatch
    - celery.worker
  commands:
    - celery --version
    - celery worker --help
    - celery beat --help
    - celery multi help
    - celery shell --help
    - pytest t/unit      # [py3k]

about:
  home: http://celeryproject.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Distributed Task Queue
  dev_url: https://github.com/celery/celery
  doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
  recipe-maintainers:
    - kwilcox
    - pmlandwehr
    - sodre
    - igortg
    - mcs07
